import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		
		int counter = 0, twoC = 0, threeC = 0,
		fourC = 0, CommoNum = 0;
		double rNum = 0, Avg = 0;
		char FirstGender = ' ', NextGender = ' ';
		for (int i = 1; i <= T; i++){
			rNum = generator.nextDouble();
			if (rNum > 0.5){
			FirstGender = 'b';
			} else {
				FirstGender = 'g';
			}
			NextGender = FirstGender;
			counter = 1;
			Avg ++;
			
			while (NextGender == FirstGender){
				rNum = generator.nextDouble();
				if (rNum > 0.5){
					NextGender = 'b';
				} else {
					NextGender = 'g';
				}
				counter ++;
				Avg ++;
			}
			
			if (counter == 2){
				twoC++;
			} else if (counter == 3){
				threeC++;
			} else {
				fourC++;
			}
		}
			
		Avg = Avg/T;
		CommoNum = Math.max(twoC, threeC);
		CommoNum = Math.max(CommoNum, fourC);
		
		System.out.println("Average: " + Avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + twoC);
		System.out.println("Number of families with 3 children: " + threeC);
		System.out.println("Number of families with 4 or more children: " + fourC);
		
		if (CommoNum == fourC){
			System.out.println("The most common number of children is 4 or more.");
		} else if (CommoNum == threeC){
		System.out.println("The most common number of children is 3.");
		} else {
		System.out.println("The most common number of children is 2.");
	}
}
}